### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by notrespire** [kiosion/shadow#1]
This looks so sweet. It's exactly what I'm looking for.

Are the login credentials available to run locally? 

Can't wait for more updates!

**Comment by kiosion** [comment]
Glad to hear! I'm still working on this part-time as I've been quite busy lately, but I do hope to release a beta (including an installer) soon, maybe in a couple weeks!
In the meantime, you could clone the repo to test locally, although you'd have to set up the database, or config the .env file for S3, manually
